# _config.yml

title: PeakCL
author: PeakCL
description: Développement web, création de sites web, applications web, identité visuelle, freelance
url: "https://peakcl.com"
baseurl: ""

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag