# _config.yml

title: PeakCL
author: PeakCL
description: Développement web, création de sites web, applications web, identité visuelle, freelance
url: "https://peakcl.com"
baseurl: ""
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate-v2

locale: fr_FR.UTF-8

pagination:
  enabled: true
  per_page: 6
  permalink: 'blog/page:num/'
  title: ':title - page :num'
  sort_field: 'date'
  sort_reverse: true

# Noms des mois en français
months_fr:
- Janvier
- Février
- Mars
- Avril
- Mai
- Juin
- Juillet
- Août
- Septembre
- Octobre
- Novembre
- Décembre