# _config.yml

title: PeakCL - Développement web
author: Charlotte Lacroix
description: Développement web, design et graphisme
url: "https://peakcl.com"
baseurl: ""
twitter:
  username: Charlotte Lacroix
  card: summary_large_image
  social_image: /assets/logo/Logo.jbl.png

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag