# netlify.toml

[build]
  command = "npm run build"
  publish = "_site"

[build.environment]
  RUBY_VERSION = "3.4.0"       # version de Ruby utilisée localement
  NODE_VERSION = "18"          # version de Node compatible Tailwind
  BUNDLER_VERSION = "2.5.6"    # optionnel, version de bundler

# Déploiement en preview (Pull Requests)
[context.deploy-preview]
  command = "npm run build"

# Redirections
[[redirects]]
  from = "/old-page"
  to = "/new-page"
  status = 301

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
