[build]
  command = "gem install bundler -v 2.5.6 && bundle install && npm install && npm run build"
  publish = "_site"

[build.environment]
  RUBY_VERSION = "3.4.0"
  NODE_VERSION = "18"
  BUNDLER_VERSION = "2.5.6"

[context.deploy-preview]
  command = "gem install bundler -v 2.5.6 && bundle install && npm install && npm run build"

[[redirects]]
  from = "/old-page"
  to = "/new-page"
  status = 301

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
