/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RessourcesSystemeRouteImport } from './routes/ressources-systeme'
import { Route as RessourcesSiteRouteImport } from './routes/ressources-site'
import { Route as RessourcesConversionRouteImport } from './routes/ressources-conversion'
import { Route as RessourcesConfianceRouteImport } from './routes/ressources-confiance'
import { Route as QuiSuisJeRouteImport } from './routes/qui-suis-je'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PacksRouteImport } from './routes/packs'
import { Route as MerciDiagnosticRouteImport } from './routes/merci-diagnostic'
import { Route as MerciBriefRouteImport } from './routes/merci-brief'
import { Route as MerciRouteImport } from './routes/merci'
import { Route as DiagnosticRouteImport } from './routes/diagnostic'
import { Route as BriefRouteImport } from './routes/brief'
import { Route as BienvenueStrategieRouteImport } from './routes/bienvenue-strategie'
import { Route as BienvenueRouteImport } from './routes/bienvenue'
import { Route as AgenceWebGillySurIsereRouteImport } from './routes/agence-web-gilly-sur-isere'
import { Route as AgenceWebChamberyRouteImport } from './routes/agence-web-chambery'
import { Route as AgenceWebAnnecyRouteImport } from './routes/agence-web-annecy'
import { Route as AgenceWebAlbertvilleRouteImport } from './routes/agence-web-albertville'
import { Route as AgenceWebAixLesBainsRouteImport } from './routes/agence-web-aix-les-bains'
import { Route as IndexRouteImport } from './routes/index'

const RessourcesSystemeRoute = RessourcesSystemeRouteImport.update({
  id: '/ressources-systeme',
  path: '/ressources-systeme',
  getParentRoute: () => rootRouteImport,
} as any)
const RessourcesSiteRoute = RessourcesSiteRouteImport.update({
  id: '/ressources-site',
  path: '/ressources-site',
  getParentRoute: () => rootRouteImport,
} as any)
const RessourcesConversionRoute = RessourcesConversionRouteImport.update({
  id: '/ressources-conversion',
  path: '/ressources-conversion',
  getParentRoute: () => rootRouteImport,
} as any)
const RessourcesConfianceRoute = RessourcesConfianceRouteImport.update({
  id: '/ressources-confiance',
  path: '/ressources-confiance',
  getParentRoute: () => rootRouteImport,
} as any)
const QuiSuisJeRoute = QuiSuisJeRouteImport.update({
  id: '/qui-suis-je',
  path: '/qui-suis-je',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PacksRoute = PacksRouteImport.update({
  id: '/packs',
  path: '/packs',
  getParentRoute: () => rootRouteImport,
} as any)
const MerciDiagnosticRoute = MerciDiagnosticRouteImport.update({
  id: '/merci-diagnostic',
  path: '/merci-diagnostic',
  getParentRoute: () => rootRouteImport,
} as any)
const MerciBriefRoute = MerciBriefRouteImport.update({
  id: '/merci-brief',
  path: '/merci-brief',
  getParentRoute: () => rootRouteImport,
} as any)
const MerciRoute = MerciRouteImport.update({
  id: '/merci',
  path: '/merci',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticRoute = DiagnosticRouteImport.update({
  id: '/diagnostic',
  path: '/diagnostic',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefRoute = BriefRouteImport.update({
  id: '/brief',
  path: '/brief',
  getParentRoute: () => rootRouteImport,
} as any)
const BienvenueStrategieRoute = BienvenueStrategieRouteImport.update({
  id: '/bienvenue-strategie',
  path: '/bienvenue-strategie',
  getParentRoute: () => rootRouteImport,
} as any)
const BienvenueRoute = BienvenueRouteImport.update({
  id: '/bienvenue',
  path: '/bienvenue',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenceWebGillySurIsereRoute = AgenceWebGillySurIsereRouteImport.update({
  id: '/agence-web-gilly-sur-isere',
  path: '/agence-web-gilly-sur-isere',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenceWebChamberyRoute = AgenceWebChamberyRouteImport.update({
  id: '/agence-web-chambery',
  path: '/agence-web-chambery',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenceWebAnnecyRoute = AgenceWebAnnecyRouteImport.update({
  id: '/agence-web-annecy',
  path: '/agence-web-annecy',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenceWebAlbertvilleRoute = AgenceWebAlbertvilleRouteImport.update({
  id: '/agence-web-albertville',
  path: '/agence-web-albertville',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenceWebAixLesBainsRoute = AgenceWebAixLesBainsRouteImport.update({
  id: '/agence-web-aix-les-bains',
  path: '/agence-web-aix-les-bains',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agence-web-aix-les-bains': typeof AgenceWebAixLesBainsRoute
  '/agence-web-albertville': typeof AgenceWebAlbertvilleRoute
  '/agence-web-annecy': typeof AgenceWebAnnecyRoute
  '/agence-web-chambery': typeof AgenceWebChamberyRoute
  '/agence-web-gilly-sur-isere': typeof AgenceWebGillySurIsereRoute
  '/bienvenue': typeof BienvenueRoute
  '/bienvenue-strategie': typeof BienvenueStrategieRoute
  '/brief': typeof BriefRoute
  '/diagnostic': typeof DiagnosticRoute
  '/merci': typeof MerciRoute
  '/merci-brief': typeof MerciBriefRoute
  '/merci-diagnostic': typeof MerciDiagnosticRoute
  '/packs': typeof PacksRoute
  '/portfolio': typeof PortfolioRoute
  '/qui-suis-je': typeof QuiSuisJeRoute
  '/ressources-confiance': typeof RessourcesConfianceRoute
  '/ressources-conversion': typeof RessourcesConversionRoute
  '/ressources-site': typeof RessourcesSiteRoute
  '/ressources-systeme': typeof RessourcesSystemeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agence-web-aix-les-bains': typeof AgenceWebAixLesBainsRoute
  '/agence-web-albertville': typeof AgenceWebAlbertvilleRoute
  '/agence-web-annecy': typeof AgenceWebAnnecyRoute
  '/agence-web-chambery': typeof AgenceWebChamberyRoute
  '/agence-web-gilly-sur-isere': typeof AgenceWebGillySurIsereRoute
  '/bienvenue': typeof BienvenueRoute
  '/bienvenue-strategie': typeof BienvenueStrategieRoute
  '/brief': typeof BriefRoute
  '/diagnostic': typeof DiagnosticRoute
  '/merci': typeof MerciRoute
  '/merci-brief': typeof MerciBriefRoute
  '/merci-diagnostic': typeof MerciDiagnosticRoute
  '/packs': typeof PacksRoute
  '/portfolio': typeof PortfolioRoute
  '/qui-suis-je': typeof QuiSuisJeRoute
  '/ressources-confiance': typeof RessourcesConfianceRoute
  '/ressources-conversion': typeof RessourcesConversionRoute
  '/ressources-site': typeof RessourcesSiteRoute
  '/ressources-systeme': typeof RessourcesSystemeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agence-web-aix-les-bains': typeof AgenceWebAixLesBainsRoute
  '/agence-web-albertville': typeof AgenceWebAlbertvilleRoute
  '/agence-web-annecy': typeof AgenceWebAnnecyRoute
  '/agence-web-chambery': typeof AgenceWebChamberyRoute
  '/agence-web-gilly-sur-isere': typeof AgenceWebGillySurIsereRoute
  '/bienvenue': typeof BienvenueRoute
  '/bienvenue-strategie': typeof BienvenueStrategieRoute
  '/brief': typeof BriefRoute
  '/diagnostic': typeof DiagnosticRoute
  '/merci': typeof MerciRoute
  '/merci-brief': typeof MerciBriefRoute
  '/merci-diagnostic': typeof MerciDiagnosticRoute
  '/packs': typeof PacksRoute
  '/portfolio': typeof PortfolioRoute
  '/qui-suis-je': typeof QuiSuisJeRoute
  '/ressources-confiance': typeof RessourcesConfianceRoute
  '/ressources-conversion': typeof RessourcesConversionRoute
  '/ressources-site': typeof RessourcesSiteRoute
  '/ressources-systeme': typeof RessourcesSystemeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agence-web-aix-les-bains'
    | '/agence-web-albertville'
    | '/agence-web-annecy'
    | '/agence-web-chambery'
    | '/agence-web-gilly-sur-isere'
    | '/bienvenue'
    | '/bienvenue-strategie'
    | '/brief'
    | '/diagnostic'
    | '/merci'
    | '/merci-brief'
    | '/merci-diagnostic'
    | '/packs'
    | '/portfolio'
    | '/qui-suis-je'
    | '/ressources-confiance'
    | '/ressources-conversion'
    | '/ressources-site'
    | '/ressources-systeme'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agence-web-aix-les-bains'
    | '/agence-web-albertville'
    | '/agence-web-annecy'
    | '/agence-web-chambery'
    | '/agence-web-gilly-sur-isere'
    | '/bienvenue'
    | '/bienvenue-strategie'
    | '/brief'
    | '/diagnostic'
    | '/merci'
    | '/merci-brief'
    | '/merci-diagnostic'
    | '/packs'
    | '/portfolio'
    | '/qui-suis-je'
    | '/ressources-confiance'
    | '/ressources-conversion'
    | '/ressources-site'
    | '/ressources-systeme'
  id:
    | '__root__'
    | '/'
    | '/agence-web-aix-les-bains'
    | '/agence-web-albertville'
    | '/agence-web-annecy'
    | '/agence-web-chambery'
    | '/agence-web-gilly-sur-isere'
    | '/bienvenue'
    | '/bienvenue-strategie'
    | '/brief'
    | '/diagnostic'
    | '/merci'
    | '/merci-brief'
    | '/merci-diagnostic'
    | '/packs'
    | '/portfolio'
    | '/qui-suis-je'
    | '/ressources-confiance'
    | '/ressources-conversion'
    | '/ressources-site'
    | '/ressources-systeme'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgenceWebAixLesBainsRoute: typeof AgenceWebAixLesBainsRoute
  AgenceWebAlbertvilleRoute: typeof AgenceWebAlbertvilleRoute
  AgenceWebAnnecyRoute: typeof AgenceWebAnnecyRoute
  AgenceWebChamberyRoute: typeof AgenceWebChamberyRoute
  AgenceWebGillySurIsereRoute: typeof AgenceWebGillySurIsereRoute
  BienvenueRoute: typeof BienvenueRoute
  BienvenueStrategieRoute: typeof BienvenueStrategieRoute
  BriefRoute: typeof BriefRoute
  DiagnosticRoute: typeof DiagnosticRoute
  MerciRoute: typeof MerciRoute
  MerciBriefRoute: typeof MerciBriefRoute
  MerciDiagnosticRoute: typeof MerciDiagnosticRoute
  PacksRoute: typeof PacksRoute
  PortfolioRoute: typeof PortfolioRoute
  QuiSuisJeRoute: typeof QuiSuisJeRoute
  RessourcesConfianceRoute: typeof RessourcesConfianceRoute
  RessourcesConversionRoute: typeof RessourcesConversionRoute
  RessourcesSiteRoute: typeof RessourcesSiteRoute
  RessourcesSystemeRoute: typeof RessourcesSystemeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ressources-systeme': {
      id: '/ressources-systeme'
      path: '/ressources-systeme'
      fullPath: '/ressources-systeme'
      preLoaderRoute: typeof RessourcesSystemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ressources-site': {
      id: '/ressources-site'
      path: '/ressources-site'
      fullPath: '/ressources-site'
      preLoaderRoute: typeof RessourcesSiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ressources-conversion': {
      id: '/ressources-conversion'
      path: '/ressources-conversion'
      fullPath: '/ressources-conversion'
      preLoaderRoute: typeof RessourcesConversionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ressources-confiance': {
      id: '/ressources-confiance'
      path: '/ressources-confiance'
      fullPath: '/ressources-confiance'
      preLoaderRoute: typeof RessourcesConfianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qui-suis-je': {
      id: '/qui-suis-je'
      path: '/qui-suis-je'
      fullPath: '/qui-suis-je'
      preLoaderRoute: typeof QuiSuisJeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packs': {
      id: '/packs'
      path: '/packs'
      fullPath: '/packs'
      preLoaderRoute: typeof PacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merci-diagnostic': {
      id: '/merci-diagnostic'
      path: '/merci-diagnostic'
      fullPath: '/merci-diagnostic'
      preLoaderRoute: typeof MerciDiagnosticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merci-brief': {
      id: '/merci-brief'
      path: '/merci-brief'
      fullPath: '/merci-brief'
      preLoaderRoute: typeof MerciBriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merci': {
      id: '/merci'
      path: '/merci'
      fullPath: '/merci'
      preLoaderRoute: typeof MerciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostic': {
      id: '/diagnostic'
      path: '/diagnostic'
      fullPath: '/diagnostic'
      preLoaderRoute: typeof DiagnosticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brief': {
      id: '/brief'
      path: '/brief'
      fullPath: '/brief'
      preLoaderRoute: typeof BriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bienvenue-strategie': {
      id: '/bienvenue-strategie'
      path: '/bienvenue-strategie'
      fullPath: '/bienvenue-strategie'
      preLoaderRoute: typeof BienvenueStrategieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bienvenue': {
      id: '/bienvenue'
      path: '/bienvenue'
      fullPath: '/bienvenue'
      preLoaderRoute: typeof BienvenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agence-web-gilly-sur-isere': {
      id: '/agence-web-gilly-sur-isere'
      path: '/agence-web-gilly-sur-isere'
      fullPath: '/agence-web-gilly-sur-isere'
      preLoaderRoute: typeof AgenceWebGillySurIsereRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agence-web-chambery': {
      id: '/agence-web-chambery'
      path: '/agence-web-chambery'
      fullPath: '/agence-web-chambery'
      preLoaderRoute: typeof AgenceWebChamberyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agence-web-annecy': {
      id: '/agence-web-annecy'
      path: '/agence-web-annecy'
      fullPath: '/agence-web-annecy'
      preLoaderRoute: typeof AgenceWebAnnecyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agence-web-albertville': {
      id: '/agence-web-albertville'
      path: '/agence-web-albertville'
      fullPath: '/agence-web-albertville'
      preLoaderRoute: typeof AgenceWebAlbertvilleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agence-web-aix-les-bains': {
      id: '/agence-web-aix-les-bains'
      path: '/agence-web-aix-les-bains'
      fullPath: '/agence-web-aix-les-bains'
      preLoaderRoute: typeof AgenceWebAixLesBainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgenceWebAixLesBainsRoute: AgenceWebAixLesBainsRoute,
  AgenceWebAlbertvilleRoute: AgenceWebAlbertvilleRoute,
  AgenceWebAnnecyRoute: AgenceWebAnnecyRoute,
  AgenceWebChamberyRoute: AgenceWebChamberyRoute,
  AgenceWebGillySurIsereRoute: AgenceWebGillySurIsereRoute,
  BienvenueRoute: BienvenueRoute,
  BienvenueStrategieRoute: BienvenueStrategieRoute,
  BriefRoute: BriefRoute,
  DiagnosticRoute: DiagnosticRoute,
  MerciRoute: MerciRoute,
  MerciBriefRoute: MerciBriefRoute,
  MerciDiagnosticRoute: MerciDiagnosticRoute,
  PacksRoute: PacksRoute,
  PortfolioRoute: PortfolioRoute,
  QuiSuisJeRoute: QuiSuisJeRoute,
  RessourcesConfianceRoute: RessourcesConfianceRoute,
  RessourcesConversionRoute: RessourcesConversionRoute,
  RessourcesSiteRoute: RessourcesSiteRoute,
  RessourcesSystemeRoute: RessourcesSystemeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
