/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuiSuisJeRouteImport } from './routes/qui-suis-je'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as MerciRouteImport } from './routes/merci'
import { Route as AgenceWebChamberyRouteImport } from './routes/agence-web-chambery'
import { Route as AgenceWebAnnecyRouteImport } from './routes/agence-web-annecy'
import { Route as AgenceWebAlbertvilleRouteImport } from './routes/agence-web-albertville'
import { Route as AgenceWebAixLesBainsRouteImport } from './routes/agence-web-aix-les-bains'
import { Route as IndexRouteImport } from './routes/index'

const QuiSuisJeRoute = QuiSuisJeRouteImport.update({
  id: '/qui-suis-je',
  path: '/qui-suis-je',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const MerciRoute = MerciRouteImport.update({
  id: '/merci',
  path: '/merci',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenceWebChamberyRoute = AgenceWebChamberyRouteImport.update({
  id: '/agence-web-chambery',
  path: '/agence-web-chambery',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenceWebAnnecyRoute = AgenceWebAnnecyRouteImport.update({
  id: '/agence-web-annecy',
  path: '/agence-web-annecy',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenceWebAlbertvilleRoute = AgenceWebAlbertvilleRouteImport.update({
  id: '/agence-web-albertville',
  path: '/agence-web-albertville',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenceWebAixLesBainsRoute = AgenceWebAixLesBainsRouteImport.update({
  id: '/agence-web-aix-les-bains',
  path: '/agence-web-aix-les-bains',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agence-web-aix-les-bains': typeof AgenceWebAixLesBainsRoute
  '/agence-web-albertville': typeof AgenceWebAlbertvilleRoute
  '/agence-web-annecy': typeof AgenceWebAnnecyRoute
  '/agence-web-chambery': typeof AgenceWebChamberyRoute
  '/merci': typeof MerciRoute
  '/portfolio': typeof PortfolioRoute
  '/qui-suis-je': typeof QuiSuisJeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agence-web-aix-les-bains': typeof AgenceWebAixLesBainsRoute
  '/agence-web-albertville': typeof AgenceWebAlbertvilleRoute
  '/agence-web-annecy': typeof AgenceWebAnnecyRoute
  '/agence-web-chambery': typeof AgenceWebChamberyRoute
  '/merci': typeof MerciRoute
  '/portfolio': typeof PortfolioRoute
  '/qui-suis-je': typeof QuiSuisJeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agence-web-aix-les-bains': typeof AgenceWebAixLesBainsRoute
  '/agence-web-albertville': typeof AgenceWebAlbertvilleRoute
  '/agence-web-annecy': typeof AgenceWebAnnecyRoute
  '/agence-web-chambery': typeof AgenceWebChamberyRoute
  '/merci': typeof MerciRoute
  '/portfolio': typeof PortfolioRoute
  '/qui-suis-je': typeof QuiSuisJeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agence-web-aix-les-bains'
    | '/agence-web-albertville'
    | '/agence-web-annecy'
    | '/agence-web-chambery'
    | '/merci'
    | '/portfolio'
    | '/qui-suis-je'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agence-web-aix-les-bains'
    | '/agence-web-albertville'
    | '/agence-web-annecy'
    | '/agence-web-chambery'
    | '/merci'
    | '/portfolio'
    | '/qui-suis-je'
  id:
    | '__root__'
    | '/'
    | '/agence-web-aix-les-bains'
    | '/agence-web-albertville'
    | '/agence-web-annecy'
    | '/agence-web-chambery'
    | '/merci'
    | '/portfolio'
    | '/qui-suis-je'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgenceWebAixLesBainsRoute: typeof AgenceWebAixLesBainsRoute
  AgenceWebAlbertvilleRoute: typeof AgenceWebAlbertvilleRoute
  AgenceWebAnnecyRoute: typeof AgenceWebAnnecyRoute
  AgenceWebChamberyRoute: typeof AgenceWebChamberyRoute
  MerciRoute: typeof MerciRoute
  PortfolioRoute: typeof PortfolioRoute
  QuiSuisJeRoute: typeof QuiSuisJeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/qui-suis-je': {
      id: '/qui-suis-je'
      path: '/qui-suis-je'
      fullPath: '/qui-suis-je'
      preLoaderRoute: typeof QuiSuisJeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merci': {
      id: '/merci'
      path: '/merci'
      fullPath: '/merci'
      preLoaderRoute: typeof MerciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agence-web-chambery': {
      id: '/agence-web-chambery'
      path: '/agence-web-chambery'
      fullPath: '/agence-web-chambery'
      preLoaderRoute: typeof AgenceWebChamberyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agence-web-annecy': {
      id: '/agence-web-annecy'
      path: '/agence-web-annecy'
      fullPath: '/agence-web-annecy'
      preLoaderRoute: typeof AgenceWebAnnecyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agence-web-albertville': {
      id: '/agence-web-albertville'
      path: '/agence-web-albertville'
      fullPath: '/agence-web-albertville'
      preLoaderRoute: typeof AgenceWebAlbertvilleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agence-web-aix-les-bains': {
      id: '/agence-web-aix-les-bains'
      path: '/agence-web-aix-les-bains'
      fullPath: '/agence-web-aix-les-bains'
      preLoaderRoute: typeof AgenceWebAixLesBainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgenceWebAixLesBainsRoute: AgenceWebAixLesBainsRoute,
  AgenceWebAlbertvilleRoute: AgenceWebAlbertvilleRoute,
  AgenceWebAnnecyRoute: AgenceWebAnnecyRoute,
  AgenceWebChamberyRoute: AgenceWebChamberyRoute,
  MerciRoute: MerciRoute,
  PortfolioRoute: PortfolioRoute,
  QuiSuisJeRoute: QuiSuisJeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
