/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrameProspectionRouteImport } from './routes/trame-prospection'
import { Route as RessourcesSystemeRouteImport } from './routes/ressources-systeme'
import { Route as RessourcesSiteRouteImport } from './routes/ressources-site'
import { Route as RessourcesConversionRouteImport } from './routes/ressources-conversion'
import { Route as RessourcesConfianceRouteImport } from './routes/ressources-confiance'
import { Route as ReservationAppelHorsUeRouteImport } from './routes/reservation-appel-hors-ue'
import { Route as ReservationAppelRouteImport } from './routes/reservation-appel'
import { Route as QuiSuisJeRouteImport } from './routes/qui-suis-je'
import { Route as QuestionnaireR2RouteImport } from './routes/questionnaire-r2'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PacksRouteImport } from './routes/packs'
import { Route as MerciR2RouteImport } from './routes/merci-r2'
import { Route as MerciDiagnosticRouteImport } from './routes/merci-diagnostic'
import { Route as MerciBriefRouteImport } from './routes/merci-brief'
import { Route as MerciRouteImport } from './routes/merci'
import { Route as DiagnosticRouteImport } from './routes/diagnostic'
import { Route as CreationLogoAlbertvilleRouteImport } from './routes/creation-logo-albertville'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConseilsWordpressOuSurMesureRouteImport } from './routes/conseils-wordpress-ou-sur-mesure'
import { Route as ConseilsSiteWebOuInstagramRouteImport } from './routes/conseils-site-web-ou-instagram'
import { Route as ConseilsReferencerSiteGoogleRouteImport } from './routes/conseils-referencer-site-google'
import { Route as ConseilsPrixSiteInternetRouteImport } from './routes/conseils-prix-site-internet'
import { Route as ConseilsCommunityManagerUtileRouteImport } from './routes/conseils-community-manager-utile'
import { Route as ConseilsRouteImport } from './routes/conseils'
import { Route as CommunityManagerSavoieRouteImport } from './routes/community-manager-savoie'
import { Route as BienvenueStrategieRouteImport } from './routes/bienvenue-strategie'
import { Route as BienvenueRouteImport } from './routes/bienvenue'
import { Route as BacASableVideoRouteImport } from './routes/bac-a-sable-video'
import { Route as AgenceWebGillySurIsereRouteImport } from './routes/agence-web-gilly-sur-isere'
import { Route as AgenceWebChamberyRouteImport } from './routes/agence-web-chambery'
import { Route as AgenceWebAnnecyRouteImport } from './routes/agence-web-annecy'
import { Route as AgenceWebAlbertvilleRouteImport } from './routes/agence-web-albertville'
import { Route as AgenceWebAixLesBainsRouteImport } from './routes/agence-web-aix-les-bains'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CadrageVeroniqueRouteImport } from './routes/cadrage.veronique'
import { Route as CadragePascaleRouteImport } from './routes/cadrage.pascale'
import { Route as CadrageVeroniqueMerciRouteImport } from './routes/cadrage.veronique.merci'
import { Route as CadragePascaleMerciRouteImport } from './routes/cadrage.pascale.merci'

const TrameProspectionRoute = TrameProspectionRouteImport.update({
  id: '/trame-prospection',
  path: '/trame-prospection',
  getParentRoute: () => rootRouteImport,
} as any)
const RessourcesSystemeRoute = RessourcesSystemeRouteImport.update({
  id: '/ressources-systeme',
  path: '/ressources-systeme',
  getParentRoute: () => rootRouteImport,
} as any)
const RessourcesSiteRoute = RessourcesSiteRouteImport.update({
  id: '/ressources-site',
  path: '/ressources-site',
  getParentRoute: () => rootRouteImport,
} as any)
const RessourcesConversionRoute = RessourcesConversionRouteImport.update({
  id: '/ressources-conversion',
  path: '/ressources-conversion',
  getParentRoute: () => rootRouteImport,
} as any)
const RessourcesConfianceRoute = RessourcesConfianceRouteImport.update({
  id: '/ressources-confiance',
  path: '/ressources-confiance',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationAppelHorsUeRoute = ReservationAppelHorsUeRouteImport.update({
  id: '/reservation-appel-hors-ue',
  path: '/reservation-appel-hors-ue',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationAppelRoute = ReservationAppelRouteImport.update({
  id: '/reservation-appel',
  path: '/reservation-appel',
  getParentRoute: () => rootRouteImport,
} as any)
const QuiSuisJeRoute = QuiSuisJeRouteImport.update({
  id: '/qui-suis-je',
  path: '/qui-suis-je',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionnaireR2Route = QuestionnaireR2RouteImport.update({
  id: '/questionnaire-r2',
  path: '/questionnaire-r2',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PacksRoute = PacksRouteImport.update({
  id: '/packs',
  path: '/packs',
  getParentRoute: () => rootRouteImport,
} as any)
const MerciR2Route = MerciR2RouteImport.update({
  id: '/merci-r2',
  path: '/merci-r2',
  getParentRoute: () => rootRouteImport,
} as any)
const MerciDiagnosticRoute = MerciDiagnosticRouteImport.update({
  id: '/merci-diagnostic',
  path: '/merci-diagnostic',
  getParentRoute: () => rootRouteImport,
} as any)
const MerciBriefRoute = MerciBriefRouteImport.update({
  id: '/merci-brief',
  path: '/merci-brief',
  getParentRoute: () => rootRouteImport,
} as any)
const MerciRoute = MerciRouteImport.update({
  id: '/merci',
  path: '/merci',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticRoute = DiagnosticRouteImport.update({
  id: '/diagnostic',
  path: '/diagnostic',
  getParentRoute: () => rootRouteImport,
} as any)
const CreationLogoAlbertvilleRoute = CreationLogoAlbertvilleRouteImport.update({
  id: '/creation-logo-albertville',
  path: '/creation-logo-albertville',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConseilsWordpressOuSurMesureRoute =
  ConseilsWordpressOuSurMesureRouteImport.update({
    id: '/conseils-wordpress-ou-sur-mesure',
    path: '/conseils-wordpress-ou-sur-mesure',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConseilsSiteWebOuInstagramRoute =
  ConseilsSiteWebOuInstagramRouteImport.update({
    id: '/conseils-site-web-ou-instagram',
    path: '/conseils-site-web-ou-instagram',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConseilsReferencerSiteGoogleRoute =
  ConseilsReferencerSiteGoogleRouteImport.update({
    id: '/conseils-referencer-site-google',
    path: '/conseils-referencer-site-google',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConseilsPrixSiteInternetRoute =
  ConseilsPrixSiteInternetRouteImport.update({
    id: '/conseils-prix-site-internet',
    path: '/conseils-prix-site-internet',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConseilsCommunityManagerUtileRoute =
  ConseilsCommunityManagerUtileRouteImport.update({
    id: '/conseils-community-manager-utile',
    path: '/conseils-community-manager-utile',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConseilsRoute = ConseilsRouteImport.update({
  id: '/conseils',
  path: '/conseils',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityManagerSavoieRoute = CommunityManagerSavoieRouteImport.update({
  id: '/community-manager-savoie',
  path: '/community-manager-savoie',
  getParentRoute: () => rootRouteImport,
} as any)
const BienvenueStrategieRoute = BienvenueStrategieRouteImport.update({
  id: '/bienvenue-strategie',
  path: '/bienvenue-strategie',
  getParentRoute: () => rootRouteImport,
} as any)
const BienvenueRoute = BienvenueRouteImport.update({
  id: '/bienvenue',
  path: '/bienvenue',
  getParentRoute: () => rootRouteImport,
} as any)
const BacASableVideoRoute = BacASableVideoRouteImport.update({
  id: '/bac-a-sable-video',
  path: '/bac-a-sable-video',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenceWebGillySurIsereRoute = AgenceWebGillySurIsereRouteImport.update({
  id: '/agence-web-gilly-sur-isere',
  path: '/agence-web-gilly-sur-isere',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenceWebChamberyRoute = AgenceWebChamberyRouteImport.update({
  id: '/agence-web-chambery',
  path: '/agence-web-chambery',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenceWebAnnecyRoute = AgenceWebAnnecyRouteImport.update({
  id: '/agence-web-annecy',
  path: '/agence-web-annecy',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenceWebAlbertvilleRoute = AgenceWebAlbertvilleRouteImport.update({
  id: '/agence-web-albertville',
  path: '/agence-web-albertville',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenceWebAixLesBainsRoute = AgenceWebAixLesBainsRouteImport.update({
  id: '/agence-web-aix-les-bains',
  path: '/agence-web-aix-les-bains',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CadrageVeroniqueRoute = CadrageVeroniqueRouteImport.update({
  id: '/cadrage/veronique',
  path: '/cadrage/veronique',
  getParentRoute: () => rootRouteImport,
} as any)
const CadragePascaleRoute = CadragePascaleRouteImport.update({
  id: '/cadrage/pascale',
  path: '/cadrage/pascale',
  getParentRoute: () => rootRouteImport,
} as any)
const CadrageVeroniqueMerciRoute = CadrageVeroniqueMerciRouteImport.update({
  id: '/merci',
  path: '/merci',
  getParentRoute: () => CadrageVeroniqueRoute,
} as any)
const CadragePascaleMerciRoute = CadragePascaleMerciRouteImport.update({
  id: '/merci',
  path: '/merci',
  getParentRoute: () => CadragePascaleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agence-web-aix-les-bains': typeof AgenceWebAixLesBainsRoute
  '/agence-web-albertville': typeof AgenceWebAlbertvilleRoute
  '/agence-web-annecy': typeof AgenceWebAnnecyRoute
  '/agence-web-chambery': typeof AgenceWebChamberyRoute
  '/agence-web-gilly-sur-isere': typeof AgenceWebGillySurIsereRoute
  '/bac-a-sable-video': typeof BacASableVideoRoute
  '/bienvenue': typeof BienvenueRoute
  '/bienvenue-strategie': typeof BienvenueStrategieRoute
  '/community-manager-savoie': typeof CommunityManagerSavoieRoute
  '/conseils': typeof ConseilsRoute
  '/conseils-community-manager-utile': typeof ConseilsCommunityManagerUtileRoute
  '/conseils-prix-site-internet': typeof ConseilsPrixSiteInternetRoute
  '/conseils-referencer-site-google': typeof ConseilsReferencerSiteGoogleRoute
  '/conseils-site-web-ou-instagram': typeof ConseilsSiteWebOuInstagramRoute
  '/conseils-wordpress-ou-sur-mesure': typeof ConseilsWordpressOuSurMesureRoute
  '/contact': typeof ContactRoute
  '/creation-logo-albertville': typeof CreationLogoAlbertvilleRoute
  '/diagnostic': typeof DiagnosticRoute
  '/merci': typeof MerciRoute
  '/merci-brief': typeof MerciBriefRoute
  '/merci-diagnostic': typeof MerciDiagnosticRoute
  '/merci-r2': typeof MerciR2Route
  '/packs': typeof PacksRoute
  '/portfolio': typeof PortfolioRoute
  '/questionnaire-r2': typeof QuestionnaireR2Route
  '/qui-suis-je': typeof QuiSuisJeRoute
  '/reservation-appel': typeof ReservationAppelRoute
  '/reservation-appel-hors-ue': typeof ReservationAppelHorsUeRoute
  '/ressources-confiance': typeof RessourcesConfianceRoute
  '/ressources-conversion': typeof RessourcesConversionRoute
  '/ressources-site': typeof RessourcesSiteRoute
  '/ressources-systeme': typeof RessourcesSystemeRoute
  '/trame-prospection': typeof TrameProspectionRoute
  '/cadrage/pascale': typeof CadragePascaleRouteWithChildren
  '/cadrage/veronique': typeof CadrageVeroniqueRouteWithChildren
  '/cadrage/pascale/merci': typeof CadragePascaleMerciRoute
  '/cadrage/veronique/merci': typeof CadrageVeroniqueMerciRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agence-web-aix-les-bains': typeof AgenceWebAixLesBainsRoute
  '/agence-web-albertville': typeof AgenceWebAlbertvilleRoute
  '/agence-web-annecy': typeof AgenceWebAnnecyRoute
  '/agence-web-chambery': typeof AgenceWebChamberyRoute
  '/agence-web-gilly-sur-isere': typeof AgenceWebGillySurIsereRoute
  '/bac-a-sable-video': typeof BacASableVideoRoute
  '/bienvenue': typeof BienvenueRoute
  '/bienvenue-strategie': typeof BienvenueStrategieRoute
  '/community-manager-savoie': typeof CommunityManagerSavoieRoute
  '/conseils': typeof ConseilsRoute
  '/conseils-community-manager-utile': typeof ConseilsCommunityManagerUtileRoute
  '/conseils-prix-site-internet': typeof ConseilsPrixSiteInternetRoute
  '/conseils-referencer-site-google': typeof ConseilsReferencerSiteGoogleRoute
  '/conseils-site-web-ou-instagram': typeof ConseilsSiteWebOuInstagramRoute
  '/conseils-wordpress-ou-sur-mesure': typeof ConseilsWordpressOuSurMesureRoute
  '/contact': typeof ContactRoute
  '/creation-logo-albertville': typeof CreationLogoAlbertvilleRoute
  '/diagnostic': typeof DiagnosticRoute
  '/merci': typeof MerciRoute
  '/merci-brief': typeof MerciBriefRoute
  '/merci-diagnostic': typeof MerciDiagnosticRoute
  '/merci-r2': typeof MerciR2Route
  '/packs': typeof PacksRoute
  '/portfolio': typeof PortfolioRoute
  '/questionnaire-r2': typeof QuestionnaireR2Route
  '/qui-suis-je': typeof QuiSuisJeRoute
  '/reservation-appel': typeof ReservationAppelRoute
  '/reservation-appel-hors-ue': typeof ReservationAppelHorsUeRoute
  '/ressources-confiance': typeof RessourcesConfianceRoute
  '/ressources-conversion': typeof RessourcesConversionRoute
  '/ressources-site': typeof RessourcesSiteRoute
  '/ressources-systeme': typeof RessourcesSystemeRoute
  '/trame-prospection': typeof TrameProspectionRoute
  '/cadrage/pascale': typeof CadragePascaleRouteWithChildren
  '/cadrage/veronique': typeof CadrageVeroniqueRouteWithChildren
  '/cadrage/pascale/merci': typeof CadragePascaleMerciRoute
  '/cadrage/veronique/merci': typeof CadrageVeroniqueMerciRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agence-web-aix-les-bains': typeof AgenceWebAixLesBainsRoute
  '/agence-web-albertville': typeof AgenceWebAlbertvilleRoute
  '/agence-web-annecy': typeof AgenceWebAnnecyRoute
  '/agence-web-chambery': typeof AgenceWebChamberyRoute
  '/agence-web-gilly-sur-isere': typeof AgenceWebGillySurIsereRoute
  '/bac-a-sable-video': typeof BacASableVideoRoute
  '/bienvenue': typeof BienvenueRoute
  '/bienvenue-strategie': typeof BienvenueStrategieRoute
  '/community-manager-savoie': typeof CommunityManagerSavoieRoute
  '/conseils': typeof ConseilsRoute
  '/conseils-community-manager-utile': typeof ConseilsCommunityManagerUtileRoute
  '/conseils-prix-site-internet': typeof ConseilsPrixSiteInternetRoute
  '/conseils-referencer-site-google': typeof ConseilsReferencerSiteGoogleRoute
  '/conseils-site-web-ou-instagram': typeof ConseilsSiteWebOuInstagramRoute
  '/conseils-wordpress-ou-sur-mesure': typeof ConseilsWordpressOuSurMesureRoute
  '/contact': typeof ContactRoute
  '/creation-logo-albertville': typeof CreationLogoAlbertvilleRoute
  '/diagnostic': typeof DiagnosticRoute
  '/merci': typeof MerciRoute
  '/merci-brief': typeof MerciBriefRoute
  '/merci-diagnostic': typeof MerciDiagnosticRoute
  '/merci-r2': typeof MerciR2Route
  '/packs': typeof PacksRoute
  '/portfolio': typeof PortfolioRoute
  '/questionnaire-r2': typeof QuestionnaireR2Route
  '/qui-suis-je': typeof QuiSuisJeRoute
  '/reservation-appel': typeof ReservationAppelRoute
  '/reservation-appel-hors-ue': typeof ReservationAppelHorsUeRoute
  '/ressources-confiance': typeof RessourcesConfianceRoute
  '/ressources-conversion': typeof RessourcesConversionRoute
  '/ressources-site': typeof RessourcesSiteRoute
  '/ressources-systeme': typeof RessourcesSystemeRoute
  '/trame-prospection': typeof TrameProspectionRoute
  '/cadrage/pascale': typeof CadragePascaleRouteWithChildren
  '/cadrage/veronique': typeof CadrageVeroniqueRouteWithChildren
  '/cadrage/pascale/merci': typeof CadragePascaleMerciRoute
  '/cadrage/veronique/merci': typeof CadrageVeroniqueMerciRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agence-web-aix-les-bains'
    | '/agence-web-albertville'
    | '/agence-web-annecy'
    | '/agence-web-chambery'
    | '/agence-web-gilly-sur-isere'
    | '/bac-a-sable-video'
    | '/bienvenue'
    | '/bienvenue-strategie'
    | '/community-manager-savoie'
    | '/conseils'
    | '/conseils-community-manager-utile'
    | '/conseils-prix-site-internet'
    | '/conseils-referencer-site-google'
    | '/conseils-site-web-ou-instagram'
    | '/conseils-wordpress-ou-sur-mesure'
    | '/contact'
    | '/creation-logo-albertville'
    | '/diagnostic'
    | '/merci'
    | '/merci-brief'
    | '/merci-diagnostic'
    | '/merci-r2'
    | '/packs'
    | '/portfolio'
    | '/questionnaire-r2'
    | '/qui-suis-je'
    | '/reservation-appel'
    | '/reservation-appel-hors-ue'
    | '/ressources-confiance'
    | '/ressources-conversion'
    | '/ressources-site'
    | '/ressources-systeme'
    | '/trame-prospection'
    | '/cadrage/pascale'
    | '/cadrage/veronique'
    | '/cadrage/pascale/merci'
    | '/cadrage/veronique/merci'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agence-web-aix-les-bains'
    | '/agence-web-albertville'
    | '/agence-web-annecy'
    | '/agence-web-chambery'
    | '/agence-web-gilly-sur-isere'
    | '/bac-a-sable-video'
    | '/bienvenue'
    | '/bienvenue-strategie'
    | '/community-manager-savoie'
    | '/conseils'
    | '/conseils-community-manager-utile'
    | '/conseils-prix-site-internet'
    | '/conseils-referencer-site-google'
    | '/conseils-site-web-ou-instagram'
    | '/conseils-wordpress-ou-sur-mesure'
    | '/contact'
    | '/creation-logo-albertville'
    | '/diagnostic'
    | '/merci'
    | '/merci-brief'
    | '/merci-diagnostic'
    | '/merci-r2'
    | '/packs'
    | '/portfolio'
    | '/questionnaire-r2'
    | '/qui-suis-je'
    | '/reservation-appel'
    | '/reservation-appel-hors-ue'
    | '/ressources-confiance'
    | '/ressources-conversion'
    | '/ressources-site'
    | '/ressources-systeme'
    | '/trame-prospection'
    | '/cadrage/pascale'
    | '/cadrage/veronique'
    | '/cadrage/pascale/merci'
    | '/cadrage/veronique/merci'
  id:
    | '__root__'
    | '/'
    | '/agence-web-aix-les-bains'
    | '/agence-web-albertville'
    | '/agence-web-annecy'
    | '/agence-web-chambery'
    | '/agence-web-gilly-sur-isere'
    | '/bac-a-sable-video'
    | '/bienvenue'
    | '/bienvenue-strategie'
    | '/community-manager-savoie'
    | '/conseils'
    | '/conseils-community-manager-utile'
    | '/conseils-prix-site-internet'
    | '/conseils-referencer-site-google'
    | '/conseils-site-web-ou-instagram'
    | '/conseils-wordpress-ou-sur-mesure'
    | '/contact'
    | '/creation-logo-albertville'
    | '/diagnostic'
    | '/merci'
    | '/merci-brief'
    | '/merci-diagnostic'
    | '/merci-r2'
    | '/packs'
    | '/portfolio'
    | '/questionnaire-r2'
    | '/qui-suis-je'
    | '/reservation-appel'
    | '/reservation-appel-hors-ue'
    | '/ressources-confiance'
    | '/ressources-conversion'
    | '/ressources-site'
    | '/ressources-systeme'
    | '/trame-prospection'
    | '/cadrage/pascale'
    | '/cadrage/veronique'
    | '/cadrage/pascale/merci'
    | '/cadrage/veronique/merci'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgenceWebAixLesBainsRoute: typeof AgenceWebAixLesBainsRoute
  AgenceWebAlbertvilleRoute: typeof AgenceWebAlbertvilleRoute
  AgenceWebAnnecyRoute: typeof AgenceWebAnnecyRoute
  AgenceWebChamberyRoute: typeof AgenceWebChamberyRoute
  AgenceWebGillySurIsereRoute: typeof AgenceWebGillySurIsereRoute
  BacASableVideoRoute: typeof BacASableVideoRoute
  BienvenueRoute: typeof BienvenueRoute
  BienvenueStrategieRoute: typeof BienvenueStrategieRoute
  CommunityManagerSavoieRoute: typeof CommunityManagerSavoieRoute
  ConseilsRoute: typeof ConseilsRoute
  ConseilsCommunityManagerUtileRoute: typeof ConseilsCommunityManagerUtileRoute
  ConseilsPrixSiteInternetRoute: typeof ConseilsPrixSiteInternetRoute
  ConseilsReferencerSiteGoogleRoute: typeof ConseilsReferencerSiteGoogleRoute
  ConseilsSiteWebOuInstagramRoute: typeof ConseilsSiteWebOuInstagramRoute
  ConseilsWordpressOuSurMesureRoute: typeof ConseilsWordpressOuSurMesureRoute
  ContactRoute: typeof ContactRoute
  CreationLogoAlbertvilleRoute: typeof CreationLogoAlbertvilleRoute
  DiagnosticRoute: typeof DiagnosticRoute
  MerciRoute: typeof MerciRoute
  MerciBriefRoute: typeof MerciBriefRoute
  MerciDiagnosticRoute: typeof MerciDiagnosticRoute
  MerciR2Route: typeof MerciR2Route
  PacksRoute: typeof PacksRoute
  PortfolioRoute: typeof PortfolioRoute
  QuestionnaireR2Route: typeof QuestionnaireR2Route
  QuiSuisJeRoute: typeof QuiSuisJeRoute
  ReservationAppelRoute: typeof ReservationAppelRoute
  ReservationAppelHorsUeRoute: typeof ReservationAppelHorsUeRoute
  RessourcesConfianceRoute: typeof RessourcesConfianceRoute
  RessourcesConversionRoute: typeof RessourcesConversionRoute
  RessourcesSiteRoute: typeof RessourcesSiteRoute
  RessourcesSystemeRoute: typeof RessourcesSystemeRoute
  TrameProspectionRoute: typeof TrameProspectionRoute
  CadragePascaleRoute: typeof CadragePascaleRouteWithChildren
  CadrageVeroniqueRoute: typeof CadrageVeroniqueRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trame-prospection': {
      id: '/trame-prospection'
      path: '/trame-prospection'
      fullPath: '/trame-prospection'
      preLoaderRoute: typeof TrameProspectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ressources-systeme': {
      id: '/ressources-systeme'
      path: '/ressources-systeme'
      fullPath: '/ressources-systeme'
      preLoaderRoute: typeof RessourcesSystemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ressources-site': {
      id: '/ressources-site'
      path: '/ressources-site'
      fullPath: '/ressources-site'
      preLoaderRoute: typeof RessourcesSiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ressources-conversion': {
      id: '/ressources-conversion'
      path: '/ressources-conversion'
      fullPath: '/ressources-conversion'
      preLoaderRoute: typeof RessourcesConversionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ressources-confiance': {
      id: '/ressources-confiance'
      path: '/ressources-confiance'
      fullPath: '/ressources-confiance'
      preLoaderRoute: typeof RessourcesConfianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservation-appel-hors-ue': {
      id: '/reservation-appel-hors-ue'
      path: '/reservation-appel-hors-ue'
      fullPath: '/reservation-appel-hors-ue'
      preLoaderRoute: typeof ReservationAppelHorsUeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservation-appel': {
      id: '/reservation-appel'
      path: '/reservation-appel'
      fullPath: '/reservation-appel'
      preLoaderRoute: typeof ReservationAppelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qui-suis-je': {
      id: '/qui-suis-je'
      path: '/qui-suis-je'
      fullPath: '/qui-suis-je'
      preLoaderRoute: typeof QuiSuisJeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questionnaire-r2': {
      id: '/questionnaire-r2'
      path: '/questionnaire-r2'
      fullPath: '/questionnaire-r2'
      preLoaderRoute: typeof QuestionnaireR2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packs': {
      id: '/packs'
      path: '/packs'
      fullPath: '/packs'
      preLoaderRoute: typeof PacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merci-r2': {
      id: '/merci-r2'
      path: '/merci-r2'
      fullPath: '/merci-r2'
      preLoaderRoute: typeof MerciR2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merci-diagnostic': {
      id: '/merci-diagnostic'
      path: '/merci-diagnostic'
      fullPath: '/merci-diagnostic'
      preLoaderRoute: typeof MerciDiagnosticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merci-brief': {
      id: '/merci-brief'
      path: '/merci-brief'
      fullPath: '/merci-brief'
      preLoaderRoute: typeof MerciBriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merci': {
      id: '/merci'
      path: '/merci'
      fullPath: '/merci'
      preLoaderRoute: typeof MerciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostic': {
      id: '/diagnostic'
      path: '/diagnostic'
      fullPath: '/diagnostic'
      preLoaderRoute: typeof DiagnosticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creation-logo-albertville': {
      id: '/creation-logo-albertville'
      path: '/creation-logo-albertville'
      fullPath: '/creation-logo-albertville'
      preLoaderRoute: typeof CreationLogoAlbertvilleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conseils-wordpress-ou-sur-mesure': {
      id: '/conseils-wordpress-ou-sur-mesure'
      path: '/conseils-wordpress-ou-sur-mesure'
      fullPath: '/conseils-wordpress-ou-sur-mesure'
      preLoaderRoute: typeof ConseilsWordpressOuSurMesureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conseils-site-web-ou-instagram': {
      id: '/conseils-site-web-ou-instagram'
      path: '/conseils-site-web-ou-instagram'
      fullPath: '/conseils-site-web-ou-instagram'
      preLoaderRoute: typeof ConseilsSiteWebOuInstagramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conseils-referencer-site-google': {
      id: '/conseils-referencer-site-google'
      path: '/conseils-referencer-site-google'
      fullPath: '/conseils-referencer-site-google'
      preLoaderRoute: typeof ConseilsReferencerSiteGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conseils-prix-site-internet': {
      id: '/conseils-prix-site-internet'
      path: '/conseils-prix-site-internet'
      fullPath: '/conseils-prix-site-internet'
      preLoaderRoute: typeof ConseilsPrixSiteInternetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conseils-community-manager-utile': {
      id: '/conseils-community-manager-utile'
      path: '/conseils-community-manager-utile'
      fullPath: '/conseils-community-manager-utile'
      preLoaderRoute: typeof ConseilsCommunityManagerUtileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conseils': {
      id: '/conseils'
      path: '/conseils'
      fullPath: '/conseils'
      preLoaderRoute: typeof ConseilsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-manager-savoie': {
      id: '/community-manager-savoie'
      path: '/community-manager-savoie'
      fullPath: '/community-manager-savoie'
      preLoaderRoute: typeof CommunityManagerSavoieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bienvenue-strategie': {
      id: '/bienvenue-strategie'
      path: '/bienvenue-strategie'
      fullPath: '/bienvenue-strategie'
      preLoaderRoute: typeof BienvenueStrategieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bienvenue': {
      id: '/bienvenue'
      path: '/bienvenue'
      fullPath: '/bienvenue'
      preLoaderRoute: typeof BienvenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bac-a-sable-video': {
      id: '/bac-a-sable-video'
      path: '/bac-a-sable-video'
      fullPath: '/bac-a-sable-video'
      preLoaderRoute: typeof BacASableVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agence-web-gilly-sur-isere': {
      id: '/agence-web-gilly-sur-isere'
      path: '/agence-web-gilly-sur-isere'
      fullPath: '/agence-web-gilly-sur-isere'
      preLoaderRoute: typeof AgenceWebGillySurIsereRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agence-web-chambery': {
      id: '/agence-web-chambery'
      path: '/agence-web-chambery'
      fullPath: '/agence-web-chambery'
      preLoaderRoute: typeof AgenceWebChamberyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agence-web-annecy': {
      id: '/agence-web-annecy'
      path: '/agence-web-annecy'
      fullPath: '/agence-web-annecy'
      preLoaderRoute: typeof AgenceWebAnnecyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agence-web-albertville': {
      id: '/agence-web-albertville'
      path: '/agence-web-albertville'
      fullPath: '/agence-web-albertville'
      preLoaderRoute: typeof AgenceWebAlbertvilleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agence-web-aix-les-bains': {
      id: '/agence-web-aix-les-bains'
      path: '/agence-web-aix-les-bains'
      fullPath: '/agence-web-aix-les-bains'
      preLoaderRoute: typeof AgenceWebAixLesBainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadrage/veronique': {
      id: '/cadrage/veronique'
      path: '/cadrage/veronique'
      fullPath: '/cadrage/veronique'
      preLoaderRoute: typeof CadrageVeroniqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadrage/pascale': {
      id: '/cadrage/pascale'
      path: '/cadrage/pascale'
      fullPath: '/cadrage/pascale'
      preLoaderRoute: typeof CadragePascaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadrage/veronique/merci': {
      id: '/cadrage/veronique/merci'
      path: '/merci'
      fullPath: '/cadrage/veronique/merci'
      preLoaderRoute: typeof CadrageVeroniqueMerciRouteImport
      parentRoute: typeof CadrageVeroniqueRoute
    }
    '/cadrage/pascale/merci': {
      id: '/cadrage/pascale/merci'
      path: '/merci'
      fullPath: '/cadrage/pascale/merci'
      preLoaderRoute: typeof CadragePascaleMerciRouteImport
      parentRoute: typeof CadragePascaleRoute
    }
  }
}

interface CadragePascaleRouteChildren {
  CadragePascaleMerciRoute: typeof CadragePascaleMerciRoute
}

const CadragePascaleRouteChildren: CadragePascaleRouteChildren = {
  CadragePascaleMerciRoute: CadragePascaleMerciRoute,
}

const CadragePascaleRouteWithChildren = CadragePascaleRoute._addFileChildren(
  CadragePascaleRouteChildren,
)

interface CadrageVeroniqueRouteChildren {
  CadrageVeroniqueMerciRoute: typeof CadrageVeroniqueMerciRoute
}

const CadrageVeroniqueRouteChildren: CadrageVeroniqueRouteChildren = {
  CadrageVeroniqueMerciRoute: CadrageVeroniqueMerciRoute,
}

const CadrageVeroniqueRouteWithChildren =
  CadrageVeroniqueRoute._addFileChildren(CadrageVeroniqueRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgenceWebAixLesBainsRoute: AgenceWebAixLesBainsRoute,
  AgenceWebAlbertvilleRoute: AgenceWebAlbertvilleRoute,
  AgenceWebAnnecyRoute: AgenceWebAnnecyRoute,
  AgenceWebChamberyRoute: AgenceWebChamberyRoute,
  AgenceWebGillySurIsereRoute: AgenceWebGillySurIsereRoute,
  BacASableVideoRoute: BacASableVideoRoute,
  BienvenueRoute: BienvenueRoute,
  BienvenueStrategieRoute: BienvenueStrategieRoute,
  CommunityManagerSavoieRoute: CommunityManagerSavoieRoute,
  ConseilsRoute: ConseilsRoute,
  ConseilsCommunityManagerUtileRoute: ConseilsCommunityManagerUtileRoute,
  ConseilsPrixSiteInternetRoute: ConseilsPrixSiteInternetRoute,
  ConseilsReferencerSiteGoogleRoute: ConseilsReferencerSiteGoogleRoute,
  ConseilsSiteWebOuInstagramRoute: ConseilsSiteWebOuInstagramRoute,
  ConseilsWordpressOuSurMesureRoute: ConseilsWordpressOuSurMesureRoute,
  ContactRoute: ContactRoute,
  CreationLogoAlbertvilleRoute: CreationLogoAlbertvilleRoute,
  DiagnosticRoute: DiagnosticRoute,
  MerciRoute: MerciRoute,
  MerciBriefRoute: MerciBriefRoute,
  MerciDiagnosticRoute: MerciDiagnosticRoute,
  MerciR2Route: MerciR2Route,
  PacksRoute: PacksRoute,
  PortfolioRoute: PortfolioRoute,
  QuestionnaireR2Route: QuestionnaireR2Route,
  QuiSuisJeRoute: QuiSuisJeRoute,
  ReservationAppelRoute: ReservationAppelRoute,
  ReservationAppelHorsUeRoute: ReservationAppelHorsUeRoute,
  RessourcesConfianceRoute: RessourcesConfianceRoute,
  RessourcesConversionRoute: RessourcesConversionRoute,
  RessourcesSiteRoute: RessourcesSiteRoute,
  RessourcesSystemeRoute: RessourcesSystemeRoute,
  TrameProspectionRoute: TrameProspectionRoute,
  CadragePascaleRoute: CadragePascaleRouteWithChildren,
  CadrageVeroniqueRoute: CadrageVeroniqueRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
